### ISSUE TITLE
Always show the "Oops, something happened while reading the spec" error

### ISSUE THREAD

**Issue by sibevin** [Jacob84/rspec-tree-runner#20]
I upgrade to the vision v1.0.1, but it always shows the "Oops, something happened while reading the spec" error on my all rspec files, even an empty spec as below:

```
require 'rails_helper'

RSpec.describe Buyer, type: :model do
end
```

rspec works fine:
```
$ rspec spec/models/buyer_spec.rb
No examples found.


Finished in 0.90953 seconds (files took 10.06 seconds to load)
0 examples, 0 failures
```

Here are the versions I use:

```
rspec-tree-runner 1.0.1
atom 1.11.2
ruby 2.2.3
rspec-core 3.3.2
rspec-expectations 3.3.1
rspec-mocks 3.3.2
rspec-rails 3.3.3
```

If you need any other information, just let me know.
Thank you for your great work!!

**Comment by jacobmendoza** [comment]
Thanks for reporting!.

Yeah, it seems that the spec parser is having some trouble reading the type property. Will update this issue soon.

**Comment by jacobmendoza** [comment]
@sibevin, first, thanks again for reporting and for the feedback.

I've pushed a quick and incomplete fix for the bug that you reported, as the script was failing completely to parse the spec making the package not usable. This fix should display the tree correctly. The only problem is that it won't be able to detect the identifier of the describe group. I'm working on a complete solution.

Can you let me know if this mitigates the issue?. An update is already available.

**Comment by JaKXz** [comment]
I think I'm still seeing this issue with v1.0.4 - the spec is run but I see errors thrown from atom that link me here.

**Comment by jacobmendoza** [comment]
Sorry to hear that @JaKXz,

Could you add an example of RSpec file that reproduces the issue?.

Thank you so much,

**Comment by sibevin** [comment]
Sorry for the late reply. I just try v1.0.4 and it works well for now. But another error occurs, please see #21.

Here are the versions I use:
```
rspec-tree-runner 1.0.4
atom 1.12.7

ruby 2.3.3
rspec-core 3.5.4
rspec-expectations 3.5.0
rspec-mocks 3.5.0
rspec-rails 3.5.2
rspec-support 3.5.0
```

**Comment by jacobmendoza** [comment]
Closing as fix has been attempted in #21.
